# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    # Update manifest files stored in these directories weekly
    directories:
      - "/stubs/default"
      - "/stubs/typescript"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    # Update manifest files stored in the root directory daily
    directory: "/"
    schedule:
      interval: "daily"
